server:
  port: 9083
spring:
  application:
    name: proxy
  cloud:
    gateway:
      routes:
      - id: fraud
        uri: lb://fraud-verifier
        predicates:
        - Path=/fraud-verifier/**
        filters:
        - StripPrefix=1
        - name: Retry
          args:
            retries: 3
      - id: ignored
        uri: lb://ignored
        predicates:
        - Path=/ignored/test/allowed
        filters:
        - StripPrefix=1
      - id: webflix-streaming-service
        uri: lb://webflix-streaming-service
        predicates:
        - Path=/webflix-streaming-service/**
        filters:
        - StripPrefix=1
eureka:
  client:
    healthcheck:
      enabled: true
logging:
  level:
    org.springframework: debug

management:
  endpoints:
    web:
      exposure:
        include:
          - hystrix.stream
          - metrics
          - prometheus
#hystrix:
#  command:
#    default:
#      circuitBreaker:
#        enabled: false